### ISSUE TITLE
Bug in line 105 in class ValidationRestClient

### ISSUE THREAD

**Issue by makecontact** [verifalia/verifalia-php-sdk#1]
return queryOnce($uniqueID, self::DEFAULT_REQUEST_TIMEOUT);

Should be:

return $this->queryOnce($uniqueID, self::DEFAULT_REQUEST_TIMEOUT);

**Comment by verifalia** [comment]
Thank you, @perceptiveIO: could you please submit a pull request with this fix?

**Comment by verifalia** [comment]
Thanks and sorry for the delay: issue is closed as of package version 1.1.
