### ISSUE TITLE
Problems running with PHP < 7.1

### ISSUE THREAD

**Issue by ahmadsaeed12** [verifalia/verifalia-php-sdk#4]
Class constant arrays are used in VerifaliaRestClient line 15 and VerifaliaRestClientOptions line 13, 21, 27.
This feature is only available in PHP 7.1 Since on your Packagists page the required PHP version >= 5.5.0 you must make it compatible with the versions 5.5 - 5.6.

replace const with static to make it work with all the versions it supported

**Comment by ahmadsaeed12** [comment]
Inface its not compatible with PHP < 7.1 at all.

**Comment by verifalia** [comment]
Thanks for your feedback, @ahmadsaeed12.
We are now working to include your suggestions in the new version of this SDK.

**Comment by verifalia** [comment]
@ahmadsaeed12, the latest version of our PHP SDK (v2.1) released today contains the compatibility fixes for PHP 5.6 mentioned above: I am closing this ticket, thanks.
