### ISSUE TITLE
Requires an outdated version of guzzlehttp/guzzle

### ISSUE THREAD

**Issue by balaganski** [verifalia/verifalia-php-sdk#6]
Hello,

According to the composer.json, this package specifically requires "guzzlehttp/guzzle": "~6.0"
However, this is a massively outdated version, with the current one being 7.8.1

Unfortunately, this leads to an incompatibility with other packages that require more modern Guzzle releases.
Is there a way to work around this somehow?

Regards,
Alexei Balaganski

**Comment by griccardo** [comment]
same problem

**Comment by Hilal-rzk** [comment]
+1

**Comment by verifalia** [comment]
Hello everyone,

Sorry for the late reply! We have just released version 3.1 of this library, which brings several new features and extends the support of GuzzleHTTP to version 7: this should hopefully resolve the dependency issue you encountered.

Thank you.
